version: 2

jobs:
  build:
    docker:
    - image: circleci/python:3.5
    - image: redis:3.2.4-alpine
    working_directory: ~/code
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          pipenv install -r requirements.txt
          pipenv install -r requirements_tests.txt
    - run:
        name: Link
        command: pipenv run flake8
    - run:
        name: Test
        command: PYTHONPATH=. pipenv run pytest
